### ISSUE TITLE
Add solar scanner into pipeline

### ISSUE THREAD

**Issue by atlekbai** [Zulbukharov/GoKalkan#12]
Использовать solar.appScanner

[tg link](https://t.me/go_kz/30642)

**Comment by Zulbukharov** [comment]
Я связался со специалистом "Ростелеком-Солар"  для получения демо доступа к сервису. К сожалению, "Ростелеком-Солар" не работают с физическими лицами и не могут предоставить демо доступ к сервису.
![screenshot_20211223_204513](https://user-images.githubusercontent.com/25000090/147256419-52495638-9a7b-4b0a-8c14-d78952347d63.png)

**Comment by atlekbai** [comment]
Would be good idea to add static code analyzer to the build pipeline, such as:
- [golangci-lint](https://github.com/golangci/golangci-lint)
- [go-critic](https://github.com/go-critic/go-critic)
